title: 梅田航輝
description: Works、Diary、Garden。
lang: ja
timezone: Asia/Tokyo
permalink: /diary/:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      category: diary

exclude:
  - BLOGGING.md
  - tools
